### ISSUE TITLE
Celos 

### ISSUE THREAD

**Issue by Smartninja365** [Cobweb-Aclevo/celos#51] opened 2022-04-21 20:54 UTC
Celos should have a light edition so that it's lighter therefore making the install process go by quicker and also make celos able to be installed on older devices.it would also make installing on a vm go better.

**Comment by moeenio** [comment] 2022-04-21 22:18
I'll consider this a duplicate of #37 unless you explain what could a "light edition" bring.

About your issue with not being able to run in a vm (which is the real issue here; discussed on discord), I'd try a different hypervisor.

**Comment by TheOceanBreeze** [comment] 2022-05-07 16:42
Locking this as a duplicate of #37. Please continue discussions there.

**Closed as completed by TheOceanBreeze** 2022-05-07 16:42 UTC
